<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Shared Package Metadata -->
    <Authors>Jochen Kirstätter</Authors>
    <Copyright>2026 Jochen Kirstätter</Copyright>
    <Company>IOS Indian Ocean Software Ltd</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/jochenkirstaetter/ghostfx</PackageProjectUrl>
    <RepositoryUrl>https://github.com/jochenkirstaetter/ghostfx</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <!-- Release Configuration: Embedded PDB Debug Symbols -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>embedded</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

</Project>
