<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <!-- Core Dependencies -->
    <PackageVersion Include="ReverseMarkdown" Version="4.6.0" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.6.0" />
    <PackageVersion Include="YamlDotNet" Version="16.3.0" />

    <!-- CLI Dependencies -->
    <PackageVersion Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />

    <!-- Test Dependencies -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

</Project>
