<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <!-- Core Dependencies -->
    <PackageVersion Include="ReverseMarkdown" Version="6.1.1" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />

    <!-- CLI Dependencies -->
    <PackageVersion Include="System.CommandLine" Version="2.0.11" />


    <!-- Test Dependencies -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

</Project>
